# Generated by Django 5.2 on 2025-06-21 14:20

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addMusicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('instrument_type', multiselectfield.db.fields.MultiSelectField(choices=[('GUITAR', 'Guitar'), ('PIANO', 'Piano'), ('DRUMS', 'Drums'), ('VIOLIN', 'Violin'), ('FLUTE', 'Flute')], max_length=100)),
            ],
        ),
    ]
