# Generated by Django 5.2 on 2025-06-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmusicians',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
