# Generated by Django 5.2 on 2025-07-09 12:48

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musician', '0004_profile_bio_profile_image_profile_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='addALBUM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Release_date', models.DateTimeField()),
                ('number_of_songs', models.IntegerField()),
                ('instrument_type', multiselectfield.db.fields.MultiSelectField(choices=[('Guiter', 'guiter'), ('Drum', 'drum'), ('Mixer', 'mixer'), ('DJ', 'dj'), ('Electice Guiter', 'eletic guiter')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='addMusicians',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
