# Generated by Django 5.2 on 2025-07-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musician', '0006_addalbum_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addalbum',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='addalbum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='album/image'),
        ),
    ]
