# Generated by Django 5.2 on 2025-05-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasktitle', models.CharField(max_length=200)),
                ('taskdescription', models.TextField()),
                ('iscomplete', models.BooleanField(default=False, verbose_name='Mark as Complete')),
                ('assigndate', models.DateTimeField()),
                ('category', models.ManyToManyField(to='Category.categories')),
            ],
        ),
    ]
