# Generated by Django 5.2 on 2025-05-20 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0001_initial'),
        ('Musicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addalbum',
            name='album_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Musicians.musician'),
        ),
        migrations.AlterField(
            model_name='addalbum',
            name='ratings',
            field=models.CharField(choices=[('1', '★☆☆☆☆'), ('2', '★★☆☆☆'), ('3', '★★★☆☆'), ('4', '★★★★☆'), ('5', '★★★★★')], default='5', max_length=1),
        ),
    ]
