# Generated by Django 5.2 on 2025-07-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='car_license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
