# Generated by Django 5.2 on 2025-07-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_profile_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='car_brand_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
