# Generated by Django 5.2 on 2025-05-17 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Author',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Author.author'),
        ),
    ]
