# Generated by Django 5.2 on 2025-05-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpost',
            name='category',
        ),
        migrations.AddField(
            model_name='addpost',
            name='category',
            field=models.ManyToManyField(to='Category.add_category'),
        ),
    ]
