# Generated by Django 5.2 on 2025-06-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_remove_addpost_category_addpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Author/media/uploads'),
        ),
    ]
