# Generated by Django 5.2 on 2025-06-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0007_alter_addpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Author/uploads/'),
        ),
    ]
